spring.application.name=backend

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.umwntfrhsrmmzdnwhuod
spring.datasource.password=2JdtrVGPby5DbBpF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect